#!/bin/sh

case "$LOCATION" in
	sfi) dir=/net/user/terry/r/echo/bedau ;;
	home) dir=/u/terry/r/echo/bedau ;;
esac

ECHO_LOCATION=$dir/OBJECTS
export ECHO_LOCATION

ECHO_WORLD=insects
ECHO_SITE=insects
ECHO_AGENT=fly

export ECHO_WORLD
export ECHO_SITE
export ECHO_AGENT

xterm -title 'Bedau Echo Status' -fn 9x15 -sl 1000 -sb -geometry 85x24+355+53 \
      -bg DodgerBlue1 -fg white -e $dir/Echo $@ &
