#!/bin/sh

case "$LOCATION" in
	sfi) dir=/net/user/terry/r/echo/haas ;;
	home) dir=/u/terry/r/echo/haas ;;
esac

ECHO_LOCATION=$dir/OBJECTS
export ECHO_LOCATION

ECHO_WORLD=haas-10x10
ECHO_SITE=50p
ECHO_AGENT=haas-10x10

export ECHO_WORLD
export ECHO_SITE
export ECHO_AGENT

xterm -title 'Haas Echo Status' -fn 9x15 -sl 1000 -sb -geometry 85x24+355+53 \
      -bg DodgerBlue1 -fg white -e $dir/Echo-haas &
